import React from 'react';
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Header from '../../components/Header'
import SideMenu from '../../components/SideMenu'
import Footer from '../../components/Footer'

const Layout: React.FC = (props) => {
  return (
    <div>
      <Head>
        <title>fifty fifty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <SideMenu />
        {props.children}
      </main>
      <Footer />
    </div>
  )
}

export default Layout
